const ELEMENTS = [
  { atomicNumber: 1, symbol: "H", name: "Hydrogen", group: 1, period: 1, block: "s", category: "nonmetal" },
  { atomicNumber: 2, symbol: "He", name: "Helium", group: 18, period: 1, block: "s", category: "noble gas" },
  { atomicNumber: 3, symbol: "Li", name: "Lithium", group: 1, period: 2, block: "s", category: "alkali metal" },
  { atomicNumber: 4, symbol: "Be", name: "Beryllium", group: 2, period: 2, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 5, symbol: "B", name: "Boron", group: 13, period: 2, block: "p", category: "metalloid" },
  { atomicNumber: 6, symbol: "C", name: "Carbon", group: 14, period: 2, block: "p", category: "nonmetal" },
  { atomicNumber: 7, symbol: "N", name: "Nitrogen", group: 15, period: 2, block: "p", category: "nonmetal" },
  { atomicNumber: 8, symbol: "O", name: "Oxygen", group: 16, period: 2, block: "p", category: "nonmetal" },
  { atomicNumber: 9, symbol: "F", name: "Fluorine", group: 17, period: 2, block: "p", category: "halogen" },
  { atomicNumber: 10, symbol: "Ne", name: "Neon", group: 18, period: 2, block: "p", category: "noble gas" },
  { atomicNumber: 11, symbol: "Na", name: "Sodium", group: 1, period: 3, block: "s", category: "alkali metal" },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium", group: 2, period: 3, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 13, symbol: "Al", name: "Aluminum", group: 13, period: 3, block: "p", category: "post-transition metal" },
  { atomicNumber: 14, symbol: "Si", name: "Silicon", group: 14, period: 3, block: "p", category: "metalloid" },
  { atomicNumber: 15, symbol: "P", name: "Phosphorus", group: 15, period: 3, block: "p", category: "nonmetal" },
  { atomicNumber: 16, symbol: "S", name: "Sulfur", group: 16, period: 3, block: "p", category: "nonmetal" },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", group: 17, period: 3, block: "p", category: "halogen" },
  { atomicNumber: 18, symbol: "Ar", name: "Argon", group: 18, period: 3, block: "p", category: "noble gas" },
  { atomicNumber: 19, symbol: "K", name: "Potassium", group: 1, period: 4, block: "s", category: "alkali metal" },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium", group: 2, period: 4, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", group: 3, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", group: 4, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 23, symbol: "V", name: "Vanadium", group: 5, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", group: 6, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese", group: 7, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 26, symbol: "Fe", name: "Iron", group: 8, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt", group: 9, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel", group: 10, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 29, symbol: "Cu", name: "Copper", group: 11, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc", group: 12, period: 4, block: "d", category: "transition metal" },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium", group: 13, period: 4, block: "p", category: "post-transition metal" },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium", group: 14, period: 4, block: "p", category: "metalloid" },
  { atomicNumber: 33, symbol: "As", name: "Arsenic", group: 15, period: 4, block: "p", category: "metalloid" },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", group: 16, period: 4, block: "p", category: "nonmetal" },
  { atomicNumber: 35, symbol: "Br", name: "Bromine", group: 17, period: 4, block: "p", category: "halogen" },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton", group: 18, period: 4, block: "p", category: "noble gas" },
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", group: 1, period: 5, block: "s", category: "alkali metal" },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium", group: 2, period: 5, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 39, symbol: "Y", name: "Yttrium", group: 3, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium", group: 4, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium", group: 5, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", group: 6, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium", group: 7, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", group: 8, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium", group: 9, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium", group: 10, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 47, symbol: "Ag", name: "Silver", group: 11, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium", group: 12, period: 5, block: "d", category: "transition metal" },
  { atomicNumber: 49, symbol: "In", name: "Indium", group: 13, period: 5, block: "p", category: "post-transition metal" },
  { atomicNumber: 50, symbol: "Sn", name: "Tin", group: 14, period: 5, block: "p", category: "post-transition metal" },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", group: 15, period: 5, block: "p", category: "metalloid" },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium", group: 16, period: 5, block: "p", category: "metalloid" },
  { atomicNumber: 53, symbol: "I", name: "Iodine", group: 17, period: 5, block: "p", category: "halogen" },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon", group: 18, period: 5, block: "p", category: "noble gas" },
  { atomicNumber: 55, symbol: "Cs", name: "Cesium", group: 1, period: 6, block: "s", category: "alkali metal" },
  { atomicNumber: 56, symbol: "Ba", name: "Barium", group: 2, period: 6, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", group: null, period: 6, block: "f", category: "lanthanide" },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium", group: 4, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", group: 5, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 74, symbol: "W", name: "Tungsten", group: 6, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium", group: 7, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 76, symbol: "Os", name: "Osmium", group: 8, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium", group: 9, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", group: 10, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 79, symbol: "Au", name: "Gold", group: 11, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury", group: 12, period: 6, block: "d", category: "transition metal" },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", group: 13, period: 6, block: "p", category: "post-transition metal" },
  { atomicNumber: 82, symbol: "Pb", name: "Lead", group: 14, period: 6, block: "p", category: "post-transition metal" },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth", group: 15, period: 6, block: "p", category: "post-transition metal" },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", group: 16, period: 6, block: "p", category: "metalloid" },
  { atomicNumber: 85, symbol: "At", name: "Astatine", group: 17, period: 6, block: "p", category: "halogen" },
  { atomicNumber: 86, symbol: "Rn", name: "Radon", group: 18, period: 6, block: "p", category: "noble gas" },
  { atomicNumber: 87, symbol: "Fr", name: "Francium", group: 1, period: 7, block: "s", category: "alkali metal" },
  { atomicNumber: 88, symbol: "Ra", name: "Radium", group: 2, period: 7, block: "s", category: "alkaline earth metal" },
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 92, symbol: "U", name: "Uranium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 95, symbol: "Am", name: "Americium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 100, symbol: "Fm", name: "Fermium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 101, symbol: "Md", name: "Mendelevium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 102, symbol: "No", name: "Nobelium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", group: null, period: 7, block: "f", category: "actinide" },
  { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", group: 4, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 105, symbol: "Db", name: "Dubnium", group: 5, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", group: 6, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 107, symbol: "Bh", name: "Bohrium", group: 7, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 108, symbol: "Hs", name: "Hassium", group: 8, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", group: 9, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", group: 10, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", group: 11, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 112, symbol: "Cn", name: "Copernicium", group: 12, period: 7, block: "d", category: "transition metal" },
  { atomicNumber: 113, symbol: "Nh", name: "Nihonium", group: 13, period: 7, block: "p", category: "post-transition metal" },
  { atomicNumber: 114, symbol: "Fl", name: "Flerovium", group: 14, period: 7, block: "p", category: "post-transition metal" },
  { atomicNumber: 115, symbol: "Mc", name: "Moscovium", group: 15, period: 7, block: "p", category: "post-transition metal" },
  { atomicNumber: 116, symbol: "Lv", name: "Livermorium", group: 16, period: 7, block: "p", category: "post-transition metal" },
  { atomicNumber: 117, symbol: "Ts", name: "Tennessine", group: 17, period: 7, block: "p", category: "halogen" },
  { atomicNumber: 118, symbol: "Og", name: "Oganesson", group: 18, period: 7, block: "p", category: "noble gas" }
];
// Auto-generated supplemental element data (must-know properties) keyed by atomic number
const ELEMENT_DETAILS = {
  1: { mass: 1.008, phase: 'Gas', density: 0.08988, melt: 13.99, boil: 20.271, econfig: '1s1', electroneg: 2.2, discoveredBy: 'Henry Cavendish', appearance: 'colorless gas', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Hydrogen' },
  2: { mass: 4.0026022, phase: 'Gas', density: 0.1786, melt: 0.95, boil: 4.222, econfig: '1s2', electroneg: null, discoveredBy: 'Pierre Janssen', appearance: 'colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Helium' },
  3: { mass: 6.94, phase: 'Solid', density: 0.534, melt: 453.65, boil: 1603, econfig: '[He] 2s1', electroneg: 0.98, discoveredBy: 'Johan August Arfwedson', appearance: 'silvery-white', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Lithium' },
  4: { mass: 9.01218315, phase: 'Solid', density: 1.85, melt: 1560, boil: 2742, econfig: '[He] 2s2', electroneg: 1.57, discoveredBy: 'Louis Nicolas Vauquelin', appearance: 'white-gray metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Beryllium' },
  5: { mass: 10.81, phase: 'Solid', density: 2.08, melt: 2349, boil: 4200, econfig: '[He] 2s2 2p1', electroneg: 2.04, discoveredBy: 'Joseph Louis Gay-Lussac', appearance: 'black-brown', valence: 3, wiki: 'https://en.wikipedia.org/wiki/Boron' },
  6: { mass: 12.011, phase: 'Solid', density: 1.821, melt: null, boil: null, econfig: '[He] 2s2 2p2', electroneg: 2.55, discoveredBy: 'Ancient Egypt', appearance: null, valence: 4, wiki: 'https://en.wikipedia.org/wiki/Carbon' },
  7: { mass: 14.007, phase: 'Gas', density: 1.251, melt: 63.15, boil: 77.355, econfig: '[He] 2s2 2p3', electroneg: 3.04, discoveredBy: 'Daniel Rutherford', appearance: 'colorless gas, liquid or solid', valence: 5, wiki: 'https://en.wikipedia.org/wiki/Nitrogen' },
  8: { mass: 15.999, phase: 'Gas', density: 1.429, melt: 54.36, boil: 90.188, econfig: '[He] 2s2 2p4', electroneg: 3.44, discoveredBy: 'Carl Wilhelm Scheele', appearance: null, valence: 6, wiki: 'https://en.wikipedia.org/wiki/Oxygen' },
  9: { mass: 18.9984031636, phase: 'Gas', density: 1.696, melt: 53.48, boil: 85.03, econfig: '[He] 2s2 2p5', electroneg: 3.98, discoveredBy: 'André-Marie Ampère', appearance: null, valence: 7, wiki: 'https://en.wikipedia.org/wiki/Fluorine' },
  10: { mass: 20.17976, phase: 'Gas', density: 0.9002, melt: 24.56, boil: 27.104, econfig: '[He] 2s2 2p6', electroneg: null, discoveredBy: 'Morris Travers', appearance: 'colorless gas exhibiting an orange-red glow when placed in a high voltage electric field', valence: 8, wiki: 'https://en.wikipedia.org/wiki/Neon' },
  11: { mass: 22.989769282, phase: 'Solid', density: 0.968, melt: 370.944, boil: 1156.09, econfig: '[Ne] 3s1', electroneg: 0.93, discoveredBy: 'Humphry Davy', appearance: 'silvery white metallic', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Sodium' },
  12: { mass: 24.305, phase: 'Solid', density: 1.738, melt: 923, boil: 1363, econfig: '[Ne] 3s2', electroneg: 1.31, discoveredBy: 'Joseph Black', appearance: 'shiny grey solid', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Magnesium' },
  13: { mass: 26.98153857, phase: 'Solid', density: 2.7, melt: 933.47, boil: 2743, econfig: '[Ne] 3s2 3p1', electroneg: 1.61, discoveredBy: null, appearance: 'silvery gray metallic', valence: 3, wiki: 'https://en.wikipedia.org/wiki/Aluminium' },
  14: { mass: 28.085, phase: 'Solid', density: 2.329, melt: 1687, boil: 3538, econfig: '[Ne] 3s2 3p2', electroneg: 1.9, discoveredBy: 'Jöns Jacob Berzelius', appearance: 'crystalline, reflective with bluish-tinged faces', valence: 4, wiki: 'https://en.wikipedia.org/wiki/Silicon' },
  15: { mass: 30.9737619985, phase: 'Solid', density: 1.823, melt: null, boil: null, econfig: '[Ne] 3s2 3p3', electroneg: 2.19, discoveredBy: 'Hennig Brand', appearance: 'colourless, waxy white, yellow, scarlet, red, violet, black', valence: 5, wiki: 'https://en.wikipedia.org/wiki/Phosphorus' },
  16: { mass: 32.06, phase: 'Solid', density: 2.07, melt: 388.36, boil: 717.8, econfig: '[Ne] 3s2 3p4', electroneg: 2.58, discoveredBy: 'Ancient china', appearance: 'lemon yellow sintered microcrystals', valence: 6, wiki: 'https://en.wikipedia.org/wiki/Sulfur' },
  17: { mass: 35.45, phase: 'Gas', density: 3.2, melt: 171.6, boil: 239.11, econfig: '[Ne] 3s2 3p5', electroneg: 3.16, discoveredBy: 'Carl Wilhelm Scheele', appearance: 'pale yellow-green gas', valence: 7, wiki: 'https://en.wikipedia.org/wiki/Chlorine' },
  18: { mass: 39.9481, phase: 'Gas', density: 1.784, melt: 83.81, boil: 87.302, econfig: '[Ne] 3s2 3p6', electroneg: null, discoveredBy: 'Lord Rayleigh', appearance: 'colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field', valence: 8, wiki: 'https://en.wikipedia.org/wiki/Argon' },
  19: { mass: 39.09831, phase: 'Solid', density: 0.862, melt: 336.7, boil: 1032, econfig: '[Ar] 4s1', electroneg: 0.82, discoveredBy: 'Humphry Davy', appearance: 'silvery gray', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Potassium' },
  20: { mass: 40.0784, phase: 'Solid', density: 1.55, melt: 1115, boil: 1757, econfig: '[Ar] 4s2', electroneg: 1, discoveredBy: 'Humphry Davy', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Calcium' },
  21: { mass: 44.9559085, phase: 'Solid', density: 2.985, melt: 1814, boil: 3109, econfig: '[Ar] 3d1 4s2', electroneg: 1.36, discoveredBy: 'Lars Fredrik Nilson', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Scandium' },
  22: { mass: 47.8671, phase: 'Solid', density: 4.506, melt: 1941, boil: 3560, econfig: '[Ar] 3d2 4s2', electroneg: 1.54, discoveredBy: 'William Gregor', appearance: 'silvery grey-white metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Titanium' },
  23: { mass: 50.94151, phase: 'Solid', density: 6, melt: 2183, boil: 3680, econfig: '[Ar] 3d3 4s2', electroneg: 1.63, discoveredBy: 'Andrés Manuel del Río', appearance: 'blue-silver-grey metal', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Vanadium' },
  24: { mass: 51.99616, phase: 'Solid', density: 7.19, melt: 2180, boil: 2944, econfig: '[Ar] 3d5 4s1', electroneg: 1.66, discoveredBy: 'Louis Nicolas Vauquelin', appearance: 'silvery metallic', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Chromium' },
  25: { mass: 54.9380443, phase: 'Solid', density: 7.21, melt: 1519, boil: 2334, econfig: '[Ar] 3d5 4s2', electroneg: 1.55, discoveredBy: 'Torbern Olof Bergman', appearance: 'silvery metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Manganese' },
  26: { mass: 55.8452, phase: 'Solid', density: 7.874, melt: 1811, boil: 3134, econfig: '[Ar] 3d6 4s2', electroneg: 1.83, discoveredBy: '5000 BC', appearance: 'lustrous metallic with a grayish tinge', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Iron' },
  27: { mass: 58.9331944, phase: 'Solid', density: 8.9, melt: 1768, boil: 3200, econfig: '[Ar] 3d7 4s2', electroneg: 1.88, discoveredBy: 'Georg Brandt', appearance: 'hard lustrous gray metal', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Cobalt' },
  28: { mass: 58.69344, phase: 'Solid', density: 8.908, melt: 1728, boil: 3003, econfig: '[Ar] 3d8 4s2', electroneg: 1.91, discoveredBy: 'Axel Fredrik Cronstedt', appearance: 'lustrous, metallic, and silver with a gold tinge', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Nickel' },
  29: { mass: 63.5463, phase: 'Solid', density: 8.96, melt: 1357.77, boil: 2835, econfig: '[Ar] 3d10 4s1', electroneg: 1.9, discoveredBy: 'Middle East', appearance: 'red-orange metallic luster', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Copper' },
  30: { mass: 65.382, phase: 'Solid', density: 7.14, melt: 692.68, boil: 1180, econfig: '[Ar] 3d10 4s2', electroneg: 1.65, discoveredBy: 'India', appearance: 'silver-gray', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Zinc' },
  31: { mass: 69.7231, phase: 'Solid', density: 5.91, melt: 302.9146, boil: 2673, econfig: '[Ar] 3d10 4s2 4p1', electroneg: 1.81, discoveredBy: 'Lecoq de Boisbaudran', appearance: 'silver-white', valence: 3, wiki: 'https://en.wikipedia.org/wiki/Gallium' },
  32: { mass: 72.6308, phase: 'Solid', density: 5.323, melt: 1211.4, boil: 3106, econfig: '[Ar] 3d10 4s2 4p2', electroneg: 2.01, discoveredBy: 'Clemens Winkler', appearance: 'grayish-white', valence: 4, wiki: 'https://en.wikipedia.org/wiki/Germanium' },
  33: { mass: 74.9215956, phase: 'Solid', density: 5.727, melt: null, boil: null, econfig: '[Ar] 3d10 4s2 4p3', electroneg: 2.18, discoveredBy: 'Bronze Age', appearance: 'metallic grey', valence: 5, wiki: 'https://en.wikipedia.org/wiki/Arsenic' },
  34: { mass: 78.9718, phase: 'Solid', density: 4.81, melt: 494, boil: 958, econfig: '[Ar] 3d10 4s2 4p4', electroneg: 2.55, discoveredBy: 'Jöns Jakob Berzelius', appearance: 'black, red, and gray (not pictured) allotropes', valence: 6, wiki: 'https://en.wikipedia.org/wiki/Selenium' },
  35: { mass: 79.904, phase: 'Liquid', density: 3.1028, melt: 265.8, boil: 332, econfig: '[Ar] 3d10 4s2 4p5', electroneg: 2.96, discoveredBy: 'Antoine Jérôme Balard', appearance: null, valence: 7, wiki: 'https://en.wikipedia.org/wiki/Bromine' },
  36: { mass: 83.7982, phase: 'Gas', density: 3.749, melt: 115.78, boil: 119.93, econfig: '[Ar] 3d10 4s2 4p6', electroneg: 3, discoveredBy: 'William Ramsay', appearance: 'colorless gas, exhibiting a whitish glow in a high electric field', valence: 8, wiki: 'https://en.wikipedia.org/wiki/Krypton' },
  37: { mass: 85.46783, phase: 'Solid', density: 1.532, melt: 312.45, boil: 961, econfig: '[Kr] 5s1', electroneg: 0.82, discoveredBy: 'Robert Bunsen', appearance: 'grey white', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Rubidium' },
  38: { mass: 87.621, phase: 'Solid', density: 2.64, melt: 1050, boil: 1650, econfig: '[Kr] 5s2', electroneg: 0.95, discoveredBy: 'William Cruickshank (chemist)', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Strontium' },
  39: { mass: 88.905842, phase: 'Solid', density: 4.472, melt: 1799, boil: 3203, econfig: '[Kr] 4d1 5s2', electroneg: 1.22, discoveredBy: 'Johan Gadolin', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Yttrium' },
  40: { mass: 91.2242, phase: 'Solid', density: 6.52, melt: 2128, boil: 4650, econfig: '[Kr] 4d2 5s2', electroneg: 1.33, discoveredBy: 'Martin Heinrich Klaproth', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Zirconium' },
  41: { mass: 92.906372, phase: 'Solid', density: 8.57, melt: 2750, boil: 5017, econfig: '[Kr] 4d4 5s1', electroneg: 1.6, discoveredBy: 'Charles Hatchett', appearance: 'gray metallic, bluish when oxidized', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Niobium' },
  42: { mass: 95.951, phase: 'Solid', density: 10.28, melt: 2896, boil: 4912, econfig: '[Kr] 4d5 5s1', electroneg: 2.16, discoveredBy: 'Carl Wilhelm Scheele', appearance: 'gray metallic', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Molybdenum' },
  43: { mass: 98, phase: 'Solid', density: 11, melt: 2430, boil: 4538, econfig: '[Kr] 4d5 5s2', electroneg: 1.9, discoveredBy: 'Emilio Segrè', appearance: 'shiny gray metal', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Technetium' },
  44: { mass: 101.072, phase: 'Solid', density: 12.45, melt: 2607, boil: 4423, econfig: '[Kr] 4d7 5s1', electroneg: 2.2, discoveredBy: 'Karl Ernst Claus', appearance: 'silvery white metallic', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Ruthenium' },
  45: { mass: 102.905502, phase: 'Solid', density: 12.41, melt: 2237, boil: 3968, econfig: '[Kr] 4d8 5s1', electroneg: 2.28, discoveredBy: 'William Hyde Wollaston', appearance: 'silvery white metallic', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Rhodium' },
  46: { mass: 106.421, phase: 'Solid', density: 12.023, melt: 1828.05, boil: 3236, econfig: '[Kr] 4d10', electroneg: 2.2, discoveredBy: 'William Hyde Wollaston', appearance: 'silvery white', valence: 18, wiki: 'https://en.wikipedia.org/wiki/Palladium' },
  47: { mass: 107.86822, phase: 'Solid', density: 10.49, melt: 1234.93, boil: 2435, econfig: '[Kr] 4d10 5s1', electroneg: 1.93, discoveredBy: 'unknown, before 5000 BC', appearance: 'lustrous white metal', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Silver' },
  48: { mass: 112.4144, phase: 'Solid', density: 8.65, melt: 594.22, boil: 1040, econfig: '[Kr] 4d10 5s2', electroneg: 1.69, discoveredBy: 'Karl Samuel Leberecht Hermann', appearance: 'silvery bluish-gray metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Cadmium' },
  49: { mass: 114.8181, phase: 'Solid', density: 7.31, melt: 429.7485, boil: 2345, econfig: '[Kr] 4d10 5s2 5p1', electroneg: 1.78, discoveredBy: 'Ferdinand Reich', appearance: 'silvery lustrous gray', valence: 3, wiki: 'https://en.wikipedia.org/wiki/Indium' },
  50: { mass: 118.7107, phase: 'Solid', density: 7.365, melt: 505.08, boil: 2875, econfig: '[Kr] 4d10 5s2 5p2', electroneg: 1.96, discoveredBy: 'unknown, before 3500 BC', appearance: 'silvery-white (beta, β) or gray (alpha, α)', valence: 4, wiki: 'https://en.wikipedia.org/wiki/Tin' },
  51: { mass: 121.7601, phase: 'Solid', density: 6.697, melt: 903.78, boil: 1908, econfig: '[Kr] 4d10 5s2 5p3', electroneg: 2.05, discoveredBy: 'unknown, before 3000 BC', appearance: 'silvery lustrous gray', valence: 5, wiki: 'https://en.wikipedia.org/wiki/Antimony' },
  52: { mass: 127.603, phase: 'Solid', density: 6.24, melt: 722.66, boil: 1261, econfig: '[Kr] 4d10 5s2 5p4', electroneg: 2.1, discoveredBy: 'Franz-Joseph Müller von Reichenstein', appearance: null, valence: 6, wiki: 'https://en.wikipedia.org/wiki/Tellurium' },
  53: { mass: 126.904473, phase: 'Solid', density: 4.933, melt: 386.85, boil: 457.4, econfig: '[Kr] 4d10 5s2 5p5', electroneg: 2.66, discoveredBy: 'Bernard Courtois', appearance: 'lustrous metallic gray, violet as a gas', valence: 7, wiki: 'https://en.wikipedia.org/wiki/Iodine' },
  54: { mass: 131.2936, phase: 'Gas', density: 5.894, melt: 161.4, boil: 165.051, econfig: '[Kr] 4d10 5s2 5p6', electroneg: 2.6, discoveredBy: 'William Ramsay', appearance: 'colorless gas, exhibiting a blue glow when placed in a high voltage electric field', valence: 8, wiki: 'https://en.wikipedia.org/wiki/Xenon' },
  55: { mass: 132.905451966, phase: 'Solid', density: 1.93, melt: 301.7, boil: 944, econfig: '[Xe] 6s1', electroneg: 0.79, discoveredBy: 'Robert Bunsen', appearance: 'silvery gold', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Cesium' },
  56: { mass: 137.3277, phase: 'Solid', density: 3.51, melt: 1000, boil: 2118, econfig: '[Xe] 6s2', electroneg: 0.89, discoveredBy: 'Carl Wilhelm Scheele', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Barium' },
  57: { mass: 138.905477, phase: 'Solid', density: 6.162, melt: 1193, boil: 3737, econfig: '[Xe] 5d16s2', electroneg: 1.1, discoveredBy: 'Carl Gustaf Mosander', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Lanthanum' },
  58: { mass: 140.1161, phase: 'Solid', density: 6.77, melt: 1068, boil: 3716, econfig: '[Xe] 4f1 5d1 6s2', electroneg: 1.12, discoveredBy: 'Martin Heinrich Klaproth', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Cerium' },
  59: { mass: 140.907662, phase: 'Solid', density: 6.77, melt: 1208, boil: 3403, econfig: '[Xe] 4f3 6s2', electroneg: 1.13, discoveredBy: 'Carl Auer von Welsbach', appearance: 'grayish white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Praseodymium' },
  60: { mass: 144.2423, phase: 'Solid', density: 7.01, melt: 1297, boil: 3347, econfig: '[Xe] 4f4 6s2', electroneg: 1.14, discoveredBy: 'Carl Auer von Welsbach', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Neodymium' },
  61: { mass: 145, phase: 'Solid', density: 7.26, melt: 1315, boil: 3273, econfig: '[Xe] 4f5 6s2', electroneg: 1.13, discoveredBy: 'Chien Shiung Wu', appearance: 'metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Promethium' },
  62: { mass: 150.362, phase: 'Solid', density: 7.52, melt: 1345, boil: 2173, econfig: '[Xe] 4f6 6s2', electroneg: 1.17, discoveredBy: 'Lecoq de Boisbaudran', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Samarium' },
  63: { mass: 151.9641, phase: 'Solid', density: 5.264, melt: 1099, boil: 1802, econfig: '[Xe] 4f7 6s2', electroneg: 1.2, discoveredBy: 'Eugène-Anatole Demarçay', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Europium' },
  64: { mass: 157.253, phase: 'Solid', density: 7.9, melt: 1585, boil: 3273, econfig: '[Xe] 4f7 5d1 6s2', electroneg: 1.2, discoveredBy: 'Jean Charles Galissard de Marignac', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Gadolinium' },
  65: { mass: 158.925352, phase: 'Solid', density: 8.23, melt: 1629, boil: 3396, econfig: '[Xe] 4f9 6s2', electroneg: 1.1, discoveredBy: 'Carl Gustaf Mosander', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Terbium' },
  66: { mass: 162.5001, phase: 'Solid', density: 8.54, melt: 1680, boil: 2840, econfig: '[Xe] 4f10 6s2', electroneg: 1.22, discoveredBy: 'Lecoq de Boisbaudran', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Dysprosium' },
  67: { mass: 164.930332, phase: 'Solid', density: 8.79, melt: 1734, boil: 2873, econfig: '[Xe] 4f11 6s2', electroneg: 1.23, discoveredBy: 'Marc Delafontaine', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Holmium' },
  68: { mass: 167.2593, phase: 'Solid', density: 9.066, melt: 1802, boil: 3141, econfig: '[Xe] 4f12 6s2', electroneg: 1.24, discoveredBy: 'Carl Gustaf Mosander', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Erbium' },
  69: { mass: 168.934222, phase: 'Solid', density: 9.32, melt: 1818, boil: 2223, econfig: '[Xe] 4f13 6s2', electroneg: 1.25, discoveredBy: 'Per Teodor Cleve', appearance: 'silvery gray', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Thulium' },
  70: { mass: 173.0451, phase: 'Solid', density: 6.9, melt: 1097, boil: 1469, econfig: '[Xe] 4f14 6s2', electroneg: 1.1, discoveredBy: 'Jean Charles Galissard de Marignac', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Ytterbium' },
  71: { mass: 174.96681, phase: 'Solid', density: 9.841, melt: 1925, boil: 3675, econfig: '[Xe] 4f14 5d1 6s2', electroneg: 1.27, discoveredBy: 'Georges Urbain', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Lutetium' },
  72: { mass: 178.492, phase: 'Solid', density: 13.31, melt: 2506, boil: 4876, econfig: '[Xe] 4f14 5d2 6s2', electroneg: 1.3, discoveredBy: 'Dirk Coster', appearance: 'steel gray', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Hafnium' },
  73: { mass: 180.947882, phase: 'Solid', density: 16.69, melt: 3290, boil: 5731, econfig: '[Xe] 4f14 5d3 6s2', electroneg: 1.5, discoveredBy: 'Anders Gustaf Ekeberg', appearance: 'gray blue', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Tantalum' },
  74: { mass: 183.841, phase: 'Solid', density: 19.25, melt: 3695, boil: 6203, econfig: '[Xe] 4f14 5d4 6s2', electroneg: 2.36, discoveredBy: 'Carl Wilhelm Scheele', appearance: 'grayish white, lustrous', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Tungsten' },
  75: { mass: 186.2071, phase: 'Solid', density: 21.02, melt: 3459, boil: 5869, econfig: '[Xe] 4f14 5d5 6s2', electroneg: 1.9, discoveredBy: 'Masataka Ogawa', appearance: 'silvery-grayish', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Rhenium' },
  76: { mass: 190.233, phase: 'Solid', density: 22.59, melt: 3306, boil: 5285, econfig: '[Xe] 4f14 5d6 6s2', electroneg: 2.2, discoveredBy: 'Smithson Tennant', appearance: 'silvery, blue cast', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Osmium' },
  77: { mass: 192.2173, phase: 'Solid', density: 22.56, melt: 2719, boil: 4403, econfig: '[Xe] 4f14 5d7 6s2', electroneg: 2.2, discoveredBy: 'Smithson Tennant', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Iridium' },
  78: { mass: 195.0849, phase: 'Solid', density: 21.45, melt: 2041.4, boil: 4098, econfig: '[Xe] 4f14 5d9 6s1', electroneg: 2.28, discoveredBy: 'Antonio de Ulloa', appearance: 'silvery white', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Platinum' },
  79: { mass: 196.9665695, phase: 'Solid', density: 19.3, melt: 1337.33, boil: 3243, econfig: '[Xe] 4f14 5d10 6s1', electroneg: 2.54, discoveredBy: 'Middle East', appearance: 'metallic yellow', valence: 1, wiki: 'https://en.wikipedia.org/wiki/Gold' },
  80: { mass: 200.5923, phase: 'Liquid', density: 13.534, melt: 234.321, boil: 629.88, econfig: '[Xe] 4f14 5d10 6s2', electroneg: 2, discoveredBy: 'unknown, before 2000 BCE', appearance: 'silvery', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Mercury (Element)' },
  81: { mass: 204.38, phase: 'Solid', density: 11.85, melt: 577, boil: 1746, econfig: '[Xe] 4f14 5d10 6s2 6p1', electroneg: 1.62, discoveredBy: 'William Crookes', appearance: 'silvery white', valence: 3, wiki: 'https://en.wikipedia.org/wiki/Thallium' },
  82: { mass: 207.21, phase: 'Solid', density: 11.34, melt: 600.61, boil: 2022, econfig: '[Xe] 4f14 5d10 6s2 6p2', electroneg: 1.87, discoveredBy: 'Middle East', appearance: 'metallic gray', valence: 4, wiki: 'https://en.wikipedia.org/wiki/Lead_(element)' },
  83: { mass: 208.980401, phase: 'Solid', density: 9.78, melt: 544.7, boil: 1837, econfig: '[Xe] 4f14 5d10 6s2 6p3', electroneg: 2.02, discoveredBy: 'Claude François Geoffroy', appearance: 'lustrous silver', valence: 5, wiki: 'https://en.wikipedia.org/wiki/Bismuth' },
  84: { mass: 209, phase: 'Solid', density: 9.196, melt: 527, boil: 1235, econfig: '[Xe] 4f14 5d10 6s2 6p4', electroneg: 2, discoveredBy: 'Pierre Curie', appearance: 'silvery', valence: 6, wiki: 'https://en.wikipedia.org/wiki/Polonium' },
  85: { mass: 210, phase: 'Solid', density: 6.35, melt: 575, boil: 610, econfig: '[Xe] 4f14 5d10 6s2 6p5', electroneg: 2.2, discoveredBy: 'Dale R. Corson', appearance: 'unknown, probably metallic', valence: 7, wiki: 'https://en.wikipedia.org/wiki/Astatine' },
  86: { mass: 222, phase: 'Gas', density: 9.73, melt: 202, boil: 211.5, econfig: '[Xe] 4f14 5d10 6s2 6p6', electroneg: 2.2, discoveredBy: 'Friedrich Ernst Dorn', appearance: 'colorless gas, occasionally glows green or red in discharge tubes', valence: 8, wiki: 'https://en.wikipedia.org/wiki/Radon' },
  87: { mass: 223, phase: 'Solid', density: 1.87, melt: 300, boil: 950, econfig: '[Rn] 7s1', electroneg: 0.79, discoveredBy: 'Marguerite Perey', appearance: null, valence: 1, wiki: 'https://en.wikipedia.org/wiki/Francium' },
  88: { mass: 226, phase: 'Solid', density: 5.5, melt: 1233, boil: 2010, econfig: '[Rn] 7s2', electroneg: 0.9, discoveredBy: 'Pierre Curie', appearance: 'silvery white metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Radium' },
  89: { mass: 227, phase: 'Solid', density: 10, melt: 1500, boil: 3500, econfig: '[Rn] 6d1 7s2', electroneg: 1.1, discoveredBy: 'Friedrich Oskar Giesel', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Actinium' },
  90: { mass: 232.03774, phase: 'Solid', density: 11.724, melt: 2023, boil: 5061, econfig: '[Rn] 6d2 7s2', electroneg: 1.3, discoveredBy: 'Jöns Jakob Berzelius', appearance: 'silvery, often with black tarnish', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Thorium' },
  91: { mass: 231.035882, phase: 'Solid', density: 15.37, melt: 1841, boil: 4300, econfig: '[Rn] 5f2 6d1 7s2', electroneg: 1.5, discoveredBy: 'William Crookes', appearance: 'bright, silvery metallic luster', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Protactinium' },
  92: { mass: 238.028913, phase: 'Solid', density: 19.1, melt: 1405.3, boil: 4404, econfig: '[Rn] 5f3 6d1 7s2', electroneg: 1.38, discoveredBy: 'Martin Heinrich Klaproth', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Uranium' },
  93: { mass: 237, phase: 'Solid', density: 20.45, melt: 912, boil: 4447, econfig: '[Rn] 5f4 6d1 7s2', electroneg: 1.36, discoveredBy: 'Edwin McMillan', appearance: 'silvery metallic', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Neptunium' },
  94: { mass: 244, phase: 'Solid', density: 19.816, melt: 912.5, boil: 3505, econfig: '[Rn] 5f6 7s2', electroneg: 1.28, discoveredBy: 'Glenn T. Seaborg', appearance: 'silvery white, tarnishing to dark gray in air', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Plutonium' },
  95: { mass: 243, phase: 'Solid', density: 12, melt: 1449, boil: 2880, econfig: '[Rn] 5f7 7s2', electroneg: 1.13, discoveredBy: 'Glenn T. Seaborg', appearance: 'silvery white', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Americium' },
  96: { mass: 247, phase: 'Solid', density: 13.51, melt: 1613, boil: 3383, econfig: '[Rn] 5f7 6d1 7s2', electroneg: 1.28, discoveredBy: 'Glenn T. Seaborg', appearance: 'silvery metallic, glows purple in the dark', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Curium' },
  97: { mass: 247, phase: 'Solid', density: 14.78, melt: 1259, boil: 2900, econfig: '[Rn] 5f9 7s2', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: 'silvery', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Berkelium' },
  98: { mass: 251, phase: 'Solid', density: 15.1, melt: 1173, boil: 1743, econfig: '[Rn] 5f10 7s2', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: 'silvery', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Californium' },
  99: { mass: 252, phase: 'Solid', density: 8.84, melt: 1133, boil: 1269, econfig: '[Rn] 5f11 7s2', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: 'silver-colored', valence: 2, wiki: 'https://en.wikipedia.org/wiki/Einsteinium' },
  100: { mass: 257, phase: 'Solid', density: null, melt: 1800, boil: null, econfig: '[Rn] 5f12 7s2', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Fermium' },
  101: { mass: 258, phase: 'Solid', density: null, melt: 1100, boil: null, econfig: '[Rn] 5f13 7s2', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Mendelevium' },
  102: { mass: 259, phase: 'Solid', density: null, melt: 1100, boil: null, econfig: '[Rn] 5f14 7s2', electroneg: 1.3, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Nobelium' },
  103: { mass: 266, phase: 'Solid', density: null, melt: 1900, boil: null, econfig: '[Rn] 5f14 7s2 7p1', electroneg: 1.3, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: null, valence: 3, wiki: 'https://en.wikipedia.org/wiki/Lawrencium' },
  104: { mass: 267, phase: 'Solid', density: 23.2, melt: 2400, boil: 5800, econfig: '[Rn] 5f14 6d2 7s2', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Rutherfordium' },
  105: { mass: 268, phase: 'Solid', density: 29.3, melt: null, boil: null, econfig: '*[Rn] 5f14 6d3 7s2', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Dubnium' },
  106: { mass: 269, phase: 'Solid', density: 35, melt: null, boil: null, econfig: '*[Rn] 5f14 6d4 7s2', electroneg: null, discoveredBy: 'Lawrence Berkeley National Laboratory', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Seaborgium' },
  107: { mass: 270, phase: 'Solid', density: 37.1, melt: null, boil: null, econfig: '*[Rn] 5f14 6d5 7s2', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Bohrium' },
  108: { mass: 269, phase: 'Solid', density: 40.7, melt: 126, boil: null, econfig: '*[Rn] 5f14 6d6 7s2', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Hassium' },
  109: { mass: 278, phase: 'Solid', density: 37.4, melt: null, boil: null, econfig: '*[Rn] 5f14 6d7 7s2', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Meitnerium' },
  110: { mass: 281, phase: 'Solid', density: 34.8, melt: null, boil: null, econfig: '*[Rn] 5f14 6d9 7s1', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Darmstadtium' },
  111: { mass: 282, phase: 'Solid', density: 28.7, melt: null, boil: null, econfig: '*[Rn] 5f14 6d10 7s1', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Roentgenium' },
  112: { mass: 285, phase: 'Liquid', density: 14.0, melt: null, boil: 3570, econfig: '*[Rn] 5f14 6d10 7s2', electroneg: null, discoveredBy: 'Gesellschaft für Schwerionenforschung', appearance: null, valence: 2, wiki: 'https://en.wikipedia.org/wiki/Copernicium' },
  113: { mass: 286, phase: 'Solid', density: 16, melt: 700, boil: 1430, econfig: '*[Rn] 5f14 6d10 7s2 7p1', electroneg: null, discoveredBy: 'RIKEN', appearance: null, valence: 3, wiki: 'https://en.wikipedia.org/wiki/Ununtrium' },
  114: { mass: 289, phase: 'Solid', density: 14, melt: 340, boil: 420, econfig: '*[Rn] 5f14 6d10 7s2 7p2', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 4, wiki: 'https://en.wikipedia.org/wiki/Flerovium' },
  115: { mass: 289, phase: 'Solid', density: 13.5, melt: 670, boil: 1400, econfig: '*[Rn] 5f14 6d10 7s2 7p3', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 5, wiki: 'https://en.wikipedia.org/wiki/Ununpentium' },
  116: { mass: 293, phase: 'Solid', density: 12.9, melt: 709, boil: 1085, econfig: '*[Rn] 5f14 6d10 7s2 7p4', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 6, wiki: 'https://en.wikipedia.org/wiki/Livermorium' },
  117: { mass: 294, phase: 'Solid', density: 7.17, melt: 723, boil: 883, econfig: '*[Rn] 5f14 6d10 7s2 7p5', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 7, wiki: 'https://en.wikipedia.org/wiki/Tennessine' },
  118: { mass: 294, phase: 'Solid', density: 4.95, melt: null, boil: 350, econfig: '*[Rn] 5f14 6d10 7s2 7p6', electroneg: null, discoveredBy: 'Joint Institute for Nuclear Research', appearance: null, valence: 8, wiki: 'https://en.wikipedia.org/wiki/Oganesson' },
};
